
parameters:
    lemon_report.report_loader.class: "Lemon\\ReportBundle\\Entity\\ReportRepository"


services:

    twig.loader.string:
        class: "Twig_Loader_String"
        tags:
            - { name: twig.loader }

    lemon_report.report_engine:
        class: "Lemon\\ReportBundle\\Report\\Engine"
        calls:
            - [ setRepository, ["@lemon_report.orm_repository"] ]
            - [ setExecutor, ["@lemon_report.report_executor"] ]
            - [ setLogger, ["@logger"] ]

    lemon_report.orm_repository:
        class: "Lemon\\ReportBundle\\Report\\Loader\\OrmRepository"
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - "Lemon\\ReportBundle\\Entity\\Report"
        calls:
            - [ setLogger, ["@logger"] ]


    lemon_report.query_renderer:
        class: "Lemon\\ReportBundle\\Report\\Query\\Renderer"
        calls:
            - [ setTwig, ["@twig"] ]

    lemon_report.report_executor:
        class: "Lemon\\ReportBundle\\Report\\Executor"
        calls:
            - [ setConnection, [@doctrine.dbal.default_connection] ]
            - [ setLogger, ["@logger"] ]
            - [ setQueryRenderer, ["@lemon_report.query_renderer"] ]

    lemon_report.report_loader:
        class: "%lemon_report.report_loader.class%"
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - "Lemon\\ReportBundle\\Entity\\Report"
        calls:
            - [ setLogger, ["@logger"] ]

    lemon_report.report_controller: 
        class: "Lemon\\ReportBundle\\Controller\\ReportController"
        calls:
            - [ setConnection, [@doctrine.dbal.default_connection] ]
            - [ setTwig, ["@twig"] ]
            - [ setFormFactory, ["@form.factory"] ]
            - [ setReportLoader, ["@lemon_report.report_loader"] ]
            - [ setReportExecutor, ["@lemon_report.report_executor"] ]
            - [ setRouter, ["@router"] ]
            - [ setLogger, ["@logger"] ]
            - [ setReportParameterConverter, ["@lemon_report.form_report_parameter_converter"] ]
            - [ setReportEngine, ["@lemon_report.report_engine"] ]
            - [ setDebug, ['%kernel.debug%'] ]

    lemon_report.form_report_parameter_converter: 
        class: "Lemon\\ReportBundle\\Form\\ReportParameterConverter"
        calls:
            - [ setConnection, [@doctrine.dbal.default_connection] ]
            - [ setFormFactory, ["@form.factory"] ]
            - [ setLogger, ["@logger"] ]
